client_config_backend: settings
client_config:
  client_id: 428305129333-qb7gaai4r3ofm1sdk4ddgphmooko94hl.apps.googleusercontent.com
  client_secret: FWxWjHbX264E4HQMH8NKBM1V

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive