# This file describes the configuration used to set up the experiment, software version etc. 
# Configuration file should be updated once at the beginning of the experiment and shouldn’t change.

# This file's version (for backward and forward compatibility)
version: '1.0'

# Which build & protocol is this hardware corresponding to.
# See https://docs.google.com/document/d/1RxNrut1hEqf6HO6ec-6cgOr3QxeUWZpxCmhJM_be6ks/edit#heading=h.hfl0aholemb6
hardware_build: 'B2'

# Seeds specification
seeds:
 variety: 'Zehavit'  # Can be Zehavit, Bar, Bili or the name of the seeds used in the experiment
 batch: ''           # Bag serial number of the seeds used.
 number: 28          # How many seeds were placed on the agar at the begning of the experiment
 
# List camera ids that are connected to each camera position.
# If a camera is not connected set id to ''. For example camera_A_id: ''
camera_A_id: 'C04'
camera_B_id: 'C05'
camera_C_id: 'C06'
camera_D_id: 'C07'
    
led_switch_status:
    'off' #on or off
air_sense_switch_status:
    'on' #on or off
medtronic_switch_status: 
    'on' #on or off

